
server:
  port: 0

spring:
  datasource:
    url: jdbc:mysql://192.168.80.214:3306/hanwhee?serverTimezone=Asia/Seoul
    username: msa
    password: 1q2w3e4r
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  application:
    name: friend-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.80.15:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
